# Generated by Django 3.0.5 on 2020-11-29 12:27

from django.db import migrations, models
import gridfs_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=gridfs_storage.storage.GridFSStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MapMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('plays', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('mapStorageID', models.IntegerField(default=0)),
            ],
        ),
    ]
