# Generated by Django 3.0.5 on 2020-11-29 15:04

from django.db import migrations, models
import gridfs_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0002_mapfile_mapmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfile',
            name='file',
            field=models.FileField(storage=gridfs_storage.storage.GridFSStorage(location='sample/images'), upload_to=''),
        ),
    ]
