# Generated by Django 3.0.5 on 2020-11-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0007_auto_20201129_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapMetaData',
        ),
    ]
