# Generated by Django 3.0.5 on 2020-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0008_delete_mapmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('plays', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('mapStorageID', models.IntegerField(default=0)),
                ('duration', models.TimeField(auto_now=True)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
    ]
