# Generated by Django 3.0.5 on 2020-11-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0009_mapmetadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zamena',
        ),
    ]
