# Generated by Django 3.0.5 on 2020-11-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0010_delete_zamena'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmetadata',
            name='successPlays',
            field=models.IntegerField(default=0),
        ),
    ]
