# Generated by Django 3.0.5 on 2020-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0011_mapmetadata_successplays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmetadata',
            name='duration',
            field=models.TimeField(),
        ),
    ]
